spring.application.name=fitness-mono

# Database configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# redis db configuration
#spring.redis.host=${REDIS_HOST}
spring.redis.host=localhost
spring.redis.port=6379
#spring.redis.port=${REDIS_PORT}



# Logging configuration
logging.level.org.springframework=INFO
#logging.level.org.hibernate.SQL=DEBUG
logging.level.com.fitnessmono=DEBUG

# jpa configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
